name: Build Kernel

on:
  push:
    branches: [ '15.0.0-sultan' ]
  pull_request:
    branches: [ '15.0.0-sultan' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          bc \
          flex \
          bison \
          libssl-dev \
          libncurses5-dev \
          clang \
          lld \
          git \
          gcc-aarch64-linux-gnu \
          gcc-arm-linux-gnueabi

    - name: Set up environment variables
      run: |
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "SUBARCH=arm64" >> $GITHUB_ENV
        echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
        echo "CC=clang" >> $GITHUB_ENV
        echo "LD=ld.lld" >> $GITHUB_ENV

    - name: Cache build files
      uses: actions/cache@v3
      with:
        path: |
          $(pwd)/out
        key: ${{ runner.os }}-kernel-${{ hashFiles('**/Makefile', '**/*.config') }}
        restore-keys: |
          ${{ runner.os }}-kernel-

    - name: Build defconfig
      run: |
        make O=out zuma_defconfig

    - name: Compile the kernel
      run: |
        make O=out -j$(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Kernel Build
        path: |
          out/arch/arm64/boot/Image.gz-dtb
