name: Build Kernel

on:
  push:
    branches: [ '15.0.0-sultan' ]
  pull_request:
    branches: [ '15.0.0-sultan' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          bc \
          flex \
          bison \
          libssl-dev \
          libncurses5-dev \
          clang \
          lld \
          git \
          gcc-aarch64-linux-gnu \
          gcc-arm-linux-gnueabi

    - name: Build defconfig
      run: |
        make O=out ARCH=arm64 LLVM=1 zuma_defconfig

    - name: Compile the kernel
      run: |
        make O=out ARCH=arm64 LLVM=1 -j$(nproc) V=1 2>&1 | tee build.log

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Kernel Build
        path: |
          out/arch/arm64/boot/Image.gz-dtb
          build.log
