name: Build Android Kernel

on:
  push:
    branches: [ '15.0.0-sultan' ]
  pull_request:
    branches: [ '15.0.0-sultan' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t android-kernel-builder .

      - name: Run Docker container and build kernel
        run: |
          docker run --name kernel-build-container \
            -v ${{ github.workspace }}:/kernel \
            -w /kernel \
            android-kernel-builder \
            /bin/bash -c "make O=out zuma_defconfig && make O=out -j\$(nproc) V=1 2>&1 | tee build.log"

      - name: Copy build log
        run: |
          docker cp kernel-build-container:/kernel/build.log ${{ github.workspace }}

      - name: Copy artifacts from Docker container
        run: |
          docker cp kernel-build-container:/kernel/out/arch/arm64/boot/Image.gz-dtb ${{ github.workspace }}/

      - name: Remove Docker container
        run: |
          docker rm kernel-build-container

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Kernel
          path: |
            Image.gz-dtb
            build.log
