name: Build Kernel with Docker

on:
  push:
    branches: [ '15.0.0-sultan' ]
  pull_request:
    branches: [ '15.0.0-sultan' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t kernel-builder .

    - name: Compile the kernel inside Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/kernel -w /kernel kernel-builder /bin/bash -c "make O=out zuma_defconfig && make O=out -j\$(nproc)"

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Kernel Build
        path: |
          out/arch/arm64/boot/Image.gz-dtb
