name: Build Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential libncurses-dev bison flex libssl-dev libelf-dev ccache gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Set up GCC Compiler
        run: |
          git clone --depth=1 https://github.com/mvaisakh/gcc-arm64.git /opt/gcc-arm64
          git clone --depth=1 https://github.com/mvaisakh/gcc-arm.git /opt/gcc-arm
          export PATH=/opt/gcc-arm64/bin:/opt/gcc-arm/bin:$PATH

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_COMPAT=arm-linux-gnueabi-
          make O=out zuma_defconfig
          make -j$(nproc) O=out

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Kernel
          path: |
            out/arch/arm64/boot/Image.gz-dtb
            out/**/*.ko
            out/vmlinux
            out/System.map
