name: Build Android Kernel

on:
  push:
    branches: [ '15.0.0-sultan' ]
  pull_request:
    branches: [ '15.0.0-sultan' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev bison flex libssl-dev bc ccache

      - name: Set up Environment Variables
        run: |
          export PATH="/home/runner/toolchains/gcc/bin:${PATH}"
          export CROSS_COMPILE="aarch64-linux-gnu-"
          export ARCH="arm64"

      - name: Download Toolchains
        run: |
          mkdir -p /home/runner/toolchains
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gas/linux-x86 /home/runner/toolchains/gcc

      - name: Build Kernel
        run: |
          make O=out zuma_defconfig
          make O=out -j$(nproc)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Kernel
          path: |
            out/arch/arm64/boot/Image.gz-dtb
            out/**/*.ko
            out/vmlinux
            out/System.map
