name: Build Android Kernel

on:
  push:
    branches: [ '15.0.0-sultan' ]
  pull_request:
    branches: [ '15.0.0-sultan' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Build Docker image
        run: |
          docker build -t android-kernel-builder .

      - name: Run Docker container and build kernel
        run: |
          docker run -d --name kernel-build-container android-kernel-builder

      - name: Wait for the build to finish
        run: |
          docker logs -f kernel-build-container

      - name: Copy artifacts from Docker container
        run: |
          docker cp kernel-build-container:/artifacts ${{ github.workspace }}

      - name: Remove Docker container
        run: |
          docker rm kernel-build-container

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Kernel
          path: artifacts/*
